- url: https://m.lhs11.com/fxm/services/local/fxm/product/product.japi
  headers:
    cookie: RSESSIONID=VV3J9A9MMZPF0JYAHFI56UK0KZ50ZKH2
    content-type: application/json
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
                (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

- queryProductVideo_json:
    method: queryProductVideo
    params:
      variables:
        product_id: 290284
  query_json:
    order: asc,
    limit: 30,
    offset: 0,
    method: query,
    params:
      pagenumber: 1,
      pagesize: 30,
      variables:
        product_class: dzm

